//postConstants go here

//COMMENTS_GET_BY_POST_REQUEST

//COMMENT_GET_BY_POST_REQUEST

export const COMMENTS_GET_BY_POST_REQUEST = 'COMMENTS_GET_BY_POST_REQUEST';
export const COMMENTS_GET_BY_POST_SUCCESS = 'COMMENTS_GET_BY_POST_SUCCESS';
export const COMMENTS_GET_BY_POST_FAIL = 'COMMENTS_GET_BY_POST_FAIL';

export const COMMENT_GET_BY_POST_REQUEST = 'COMMENT_GET_BY_POST_REQUEST';
export const COMMENT_GET_BY_POST_SUCCESS = 'COMMENT_GET_BY_POST_SUCCESS';
export const COMMENT_GET_BY_POST_FAIL = 'COMMENT_GET_BY_POST_FAIL';

export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL';

// export const POST_EDIT_REQUEST = 'POST_EDIT_REQUEST';
// export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';
// export const POST_EDIT_FAIL = 'POST_EDIT_FAIL';

// export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
// export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
// export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';