export const DEFAULT_AVATARS_GET_REQUEST = 'DEFAULT_AVATAR_GET_REQUEST';
export const DEFAULT_AVATARS_GET_SUCCESS = 'DEFAULT_AVATAR_GET_SUCCESS';
export const DEFAULT_AVATARS_GET_FAIL = 'DEFAULT_AVATAR_GET_FAIL';
