//postConstants go here

export const POSTS_GET_REQUEST = 'POSTS_GET_REQUEST';
export const POSTS_GET_SUCCESS = 'POSTS_GET_SUCCESS';
export const POSTS_GET_FAIL = 'POSTS_GET_FAIL';

export const POST_GET_REQUEST = 'POST_GET_REQUEST';
export const POST_GET_SUCCESS = 'POST_GET_SUCCESS';
export const POST_GET_FAIL = 'POST_GET_FAIL';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';


export const POST_EDIT_REQUEST = 'POST_EDIT_REQUEST';
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';
export const POST_EDIT_FAIL = 'POST_EDIT_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';



// export const ADDRESS_SEARCH_REQUEST = 'ADDRESS_SEARCH_REQUEST';
// export const ADDRESS_SEARCH_SUCCESS = 'ADDRESS_SEARCH_SUCCESS';
// export const ADDRESS_SEARCH_FAIL = 'ADDRESS_SEARCH_FAIL';

// export const ADDRESS_CREATE_REQUEST = 'ADDRESS_CREATE_REQUEST';
// export const ADDRESS_CREATE_SUCCESS = 'ADDRESS_CREATE_SUCCESS';
// export const ADDRESS_CREATE_FAIL = 'ADDRESS_CREATE_FAIL';

// export const ADDRESS_UPDATE_REQUEST = 'ADDRESS_UPDATE_REQUEST';
// export const ADDRESS_UPDATE_SUCCESS = 'ADDRESS_UPDATE_SUCCESS';
// export const ADDRESS_UPDATE_FAIL = 'ADDRESS_UPDATE_FAIL';

// export const ADDRESS_DELETE_REQUEST = 'ADDRESS_DELETE_REQUEST';
// export const ADDRESS_DELETE_SUCCESS = 'ADDRESS_DELETE_SUCCESS';
// export const ADDRESS_DELETE_FAIL = 'ADDRESS_DELETE_FAIL';
