//profile constants go here

export const PROFILE_GET_REQUEST = 'PROFILE_GET_REQUEST'
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS'
export const PROFILE_GET_FAIL = 'PROFILE_GET_FAIL'
export const PROFILE_IS_OWNER = 'PROFILE_IS_OWNER'
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL'
export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET'




export const CLEAR_PROFILE = 'CLEAR_PROFILE'


export const MY_PROFILE_GET_REQUEST = 'MY_PROFILE_GET_REQUEST'
export const MY_PROFILE_GET_SUCCESS = 'MY_PROFILE_GET_SUCCESS'
export const MY_PROFILE_GET_FAIL = 'MY_PROFILE_GET_FAIL'