//profile constants go here

export const PROFILE_GET_REQUEST = 'PROFILE_GET_REQUEST'
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS'
export const PROFILE_GET_FAIL = 'PROFILE_GET_FAIL'
export const PROFILE_IS_OWNER = 'PROFILE_IS_OWNER'
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL'
export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET'

export const CLEAR_PROFILE = 'CLEAR_PROFILE'


export const PROFILE_GET_MY_SLUG_REQUEST = 'PROFILE_GET_MY_SLUG_REQUEST'
export const PROFILE_GET_MY_SLUG_SUCCESS = 'PROFILE_GET_MY_SLUG_SUCCESS'
export const PROFILE_GET_MY_SLUG_FAIL = 'PROFILE_GET_MY_SLUG_FAIL'
export const CLEAR_MY_SLUG = 'CLEAR_MY_SLUG'