export const SECTIONS_GET_REQUEST = 'SECTIONS_GET_REQUEST';
export const SECTIONS_GET_SUCCESS = 'SECTIONS_GET_SUCCESS';
export const SECTIONS_GET_FAIL = 'SECTIONS_GET_FAIL';

export const SECTION_GET_REQUEST = 'SECTION_GET_REQUEST';
export const SECTION_GET_SUCCESS = 'SECTION_GET_SUCCESS';
export const SECTION_GET_FAIL = 'SECTION_GET_FAIL';
export const SECTION_GET_RESET = 'SECTION_GET_RESET'
export const SECTION_GET_LOCAL_STORAGE = 'SECTION_GET_LOCAL_STORAGE'